name: ci

on:
  push:
  pull_request:

jobs:
  test:
    name: cargo checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Format check
        run: cargo fmt --check

      - name: Type check
        run: cargo check

      - name: Test
        run: cargo test
